name: publish
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: publish project
        run: |
          dotnet publish --no-self-contained -c Release -o build/release src/GrepRipper.UI

      - name: build release archive
        run: |
          $Dll = Get-Item("./build/release/GrepRipper.UI.exe")
          $VERSION = $Dll.VersionInfo.ProductVersion
          7z a -t7z -mx=9 GrepRipper-$VERSION.7z ./build/release/*
          
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "GrepRipper-*.7z"
            generateReleaseNotes: true
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}
